
import 'package:hive/hive.dart';

part 'cache_entry.g.dart'; // Will be generated by build_runner

@HiveType(typeId: 178) // Unique ID for this Hive object type
class CacheEntry extends HiveObject {
  @HiveField(0)
  final String trackId;

  @HiveField(1)
  final String url; // Original remote URL

  @HiveField(2)
  final String localPath; // Local path to the cached file/directory

  @HiveField(3)
  final DateTime cachedAt;

  @HiveField(4)
  DateTime lastAccessedAt; // For LRU

  @HiveField(5)
  final int fileSize; // Stored size in bytes (for completeness check)

  @HiveField(6)
  final bool isEncrypted; // Will be false for this phase

  @HiveField(7)
  final bool isHls; // Will be false for this phase

  CacheEntry({
    required this.trackId,
    required this.url,
    required this.localPath,
    required this.cachedAt,
    required this.lastAccessedAt,
    required this.fileSize,
    required this.isEncrypted,
    required this.isHls,
  });

  void updateAccessedTime() {
    lastAccessedAt = DateTime.now();
  }
}