import 'dart:io';
import 'package:hive/hive.dart'; // Import Hive

part 'cache_entry.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 178) // Assign a unique typeId (ensure it's not used by other Hive types)
class CacheEntry extends HiveObject { // Extend HiveObject if you want to use methods like .save(), .delete()
  @HiveField(0)
  final String trackId;

  @HiveField(1)
  final String originalUrl;

  @HiveField(2)
  final String filePath; // For MP3s

  @HiveField(3)
  final DateTime timestamp;

  @HiveField(4) // Renamed from sizeBytes for consistency with CacheMetadataStore
  final int fileSize;

  @HiveField(5)
  final bool isEncrypted;

  @HiveField(6)
  final String etag;

  @HiveField(7)
  final String lastModified;

  @HiveField(8)
  final String contentType;

  @HiveField(9)
  final String proxyUrl; // This will likely be the internal http proxy path

  // --- New fields for HLS caching ---
  @HiveField(10)
  final bool isHls;

  @HiveField(11)
  final String? hlsLocalPath; // Path to the local rewritten .m3u8 manifest file / HLS directory
  @HiveField(12)
  final String? hlsManifestFilePath;

  CacheEntry({
    required this.trackId,
    required this.originalUrl,
    required this.filePath,
    required this.timestamp,
    required this.fileSize, // Use fileSize here
    required this.isEncrypted,
    required this.etag,
    required this.lastModified,
    required this.contentType,
    required this.proxyUrl,
    // Initialize new fields
    this.isHls = false,
    this.hlsLocalPath,
    this.hlsManifestFilePath
  });

  // copyWith method to create a new instance with updated fields
  CacheEntry copyWith({
    String? trackId,
    String? originalUrl,
    String? filePath,
    DateTime? timestamp,
    int? fileSize,
    bool? isEncrypted,
    String? etag,
    String? lastModified,
    String? contentType,
    String? proxyUrl,
    bool? isHls,
    String? hlsLocalPath,
     String? hlsManifestFilePath,
  }) {
    return CacheEntry(
      trackId: trackId ?? this.trackId,
      originalUrl: originalUrl ?? this.originalUrl,
      filePath: filePath ?? this.filePath,
      timestamp: timestamp ?? this.timestamp,
      fileSize: fileSize ?? this.fileSize,
      isEncrypted: isEncrypted ?? this.isEncrypted,
      etag: etag ?? this.etag,
      lastModified: lastModified ?? this.lastModified,
      contentType: contentType ?? this.contentType,
      proxyUrl: proxyUrl ?? this.proxyUrl,
      isHls: isHls ?? this.isHls,
      hlsLocalPath: hlsLocalPath ?? this.hlsLocalPath,
      hlsManifestFilePath: hlsManifestFilePath ?? this.hlsManifestFilePath
    );
  }

  // Helper getter to determine the actual file system entity (File or Directory)
  FileSystemEntity get cacheFileEntity {
    if (isHls) {
      // For HLS, hlsLocalPath stores the base directory of the cached HLS stream
      return Directory(hlsLocalPath!);
    } else {
      // For MP3s/single files, filePath points to the actual file
      return File(filePath);
    }
  }
}